//
//  Games.swift
//  SDU Score
//
//  Created by Akzhol Imangazin on 11/21/20.
//  Copyright © 2020 Akzhol Imangazin and Madi Kupessov. All rights reserved.
//

import Foundation
import UIKit

class Games {
    var firstLabel: String?
    var firstImage: UIImage?
    var middleLabel: String?
    var secondImage: UIImage?
    var secondLabel: String?
    var lineA: [String]?
    var lineB: [String]?
    var infoA: [String]?
    var infoB: [String]?
    
    init(firstLabel: String, firstImage: UIImage, middleLabel: String, secondImage: UIImage, secondLabel: String, lineA: [String], lineB: [String], infoA: [String], infoB: [String]) {
        self.firstLabel = firstLabel
        self.firstImage = firstImage
        self.middleLabel = middleLabel
        self.secondImage = secondImage
        self.secondLabel = secondLabel
        self.lineA = lineA
        self.lineB = lineB
        self.infoA = infoA
        self.infoB = infoB
    }
}





class AllGames {
    var games: [Games] = [
        Games.init(firstLabel: "Kentau", firstImage: UIImage(named: "Kentau")!, middleLabel: "2:2", secondImage: UIImage(named: "Evolution")!, secondLabel: "Evolution", lineA: ["1 Alpamys", "3 Ayagan", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Bairamov 1", "Bekzat  3", "Berdikul 4", "Bissen 7", "Bissenbayev 8", "Sungkar 9", "Gizatov 10", "Maksatov 11", "Danabaev 17", "Kalekes 21"], infoA: ["B.Omarbek", "", "", "B.Asangali"], infoB: ["", "A.Aman", "A.Abaidullin", ""]),
        Games.init(firstLabel: "Sparta", firstImage: UIImage(named: "Sparta")!, middleLabel: "8:3", secondImage: UIImage(named: "Nomad")!, secondLabel: "Nomad", lineA: ["1 Ordabek", "3 Irisbayev", "4 Kokenov", "7 Bektemir", "8 Orman", "9 Ashirkhan", "10 Khametov", "11 Kemelkhan", "17 Khassen", "21 Kuandyk"], lineB: ["Murat 1", "Meirkhan  3", "Mukatay 4", "Kydyraliev 7", "Mamatov 8", "Omarov 9", "Sadyk 10", "Saparkhan 11", "Senalov 17", "Suyunov 21"], infoA: ["Z.Nurtuganov", "Z.Nurtuganov", "", "", "", "A.Ongarbay", "Z.Nurtuganov", "S.Torehanov(OG)", "D.Khametov", "B.Gazizov", "Z.Nurtuganov"], infoB: ["", "", "B.Ibrahim", "B.Kobilan", "Z.Nakypbek", "", "", "", "", "", ""]),
        Games.init(firstLabel: "Teachers", firstImage: UIImage(named: "Teachers")!, middleLabel: "2:0", secondImage: UIImage(named: "Rizo")!, secondLabel: "Rizo", lineA: ["1 Tangirkul", "3 Yerkeshov", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Urmanov 1", "Yerkinbek  3", "Zhumashev 4", "Mussin 7", "Kokenov 8", "Gotye 9", "Ulanov 10", "Sapargali 11", "Kabi 17", "Kenes 21"], infoA: ["Z.Agybai", "S.Vankeyev"], infoB: ["", ""]),
        Games.init(firstLabel: "Avangar", firstImage: UIImage(named: "Avangar")!, middleLabel: "1:2", secondImage: UIImage(named: "Barabar")!, secondLabel: "Barabar", lineA: ["1 Kuanysh", "3 Sagyngaly", "4 Azamat", "7 Kupesov", "8 Beibit", "9 Ospanov", "10 Imangazin", "11 Makhmutov", "17 Inkar", "21 Agmanov"], lineB: ["Zheksengaliev 1", "Ozhanov 3", "Nurtazayev 4", "Kanatov 7", "Kenzhebulatov 8", "Shah 9", "Zhumabekov 10", "Utarbaev 11", "Tagayev 17", "Serikov 21"], infoA: ["", "", "S.Azamat"], infoB: ["A.Temirbolat", "A.Temirbolat", ""]),
        Games.init(firstLabel: "Nation Army", firstImage: UIImage(named: "Nation Army")!, middleLabel: "0:2", secondImage: UIImage(named: "Alash")!, secondLabel: "Alash", lineA: ["1 Nurpeis", "3 Muratuly", "4 Muratkhan", "7 Otep", "8 Sabitov", "9 Kessikbayev", "10 Irisbayev", "11 Ganshin", "17 Bolatay", "21 Demenov"], lineB: ["Maratov 1", "Zhailybai  3", "Alibekov 4", "Begimbetov 7", "Zhekeev 8", "Bigaliev 9", "Djabasov 10", "Shukatov 11", "Nurpoldin 17", "Zholdin 21"], infoA: ["", ""], infoB: ["M.Seitov", "M.Seitov"]),
        Games.init(firstLabel: "Leicester", firstImage: UIImage(named: "Leicester")!, middleLabel: "2:0", secondImage: UIImage(named: "Antihype")!, secondLabel: "Antihype", lineA: ["1 Kokenov", "5 Muslim", "6 Zhiembay", "8 Saynov", "8 Sagyndyk", "9 Ospanov", "10 Zhapay", "16 Omirzak"], lineB: ["1 Zangar", "4 Abuov", "7 Islamkhan", "8 Alisher", "9 Akhmetov", "17 Merei", "21 Kuanov", "22 Orazaly"], infoA: ["N.Zhiembay", "S.Omirzak"], infoB: ["", ""]),
        Games.init(firstLabel: "Sunkar", firstImage: UIImage(named: "Sunkar")!, middleLabel: "4:1", secondImage: UIImage(named: "Nomad JR")!, secondLabel: "Nomad JR", lineA: ["1 Tashenov", "3 Askhat", "4 Kalilulin", "7 Tursynbaev", "8 Ali", "9 Otep", "10 Roma", "11 Kama", "17 Bolat", "21 Sharapov"], lineB: ["Balkhisov 1", "Rinatov  3", "Guzalin 4", "Kolesnik 7", "Smailov 8", "Kanatbekuly 9", "Sagaladinov 10", "Lesbek 11", "Zhasan 17", "Makat 21"], infoA: ["", "Z.Amangeldeyev", "B.Erkhanov", "E.Izbergen", "F.Batyrkhan"], infoB: ["D.Amirkhanov", "", "", "", ""]),
        
        Games.init(firstLabel: "Kentau", firstImage: UIImage(named: "Kentau")!, middleLabel: "2:2", secondImage: UIImage(named: "Evolution")!, secondLabel: "Evolution", lineA: ["1 Alpamys", "3 Ayagan", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Bairamov 1", "Bekzat  3", "Berdikul 4", "Bissen 7", "Bissenbayev 8", "Sungkar 9", "Gizatov 10", "Maksatov 11", "Danabaev 17", "Kalekes 21"], infoA: ["B.Omarbek", "", "", "B.Asangali"], infoB: ["", "A.Aman", "A.Abaidullin", ""]),
        Games.init(firstLabel: "Sparta", firstImage: UIImage(named: "Sparta")!, middleLabel: "8:3", secondImage: UIImage(named: "Nomad")!, secondLabel: "Nomad", lineA: ["1 Ordabek", "3 Irisbayev", "4 Kokenov", "7 Bektemir", "8 Orman", "9 Ashirkhan", "10 Khametov", "11 Kemelkhan", "17 Khassen", "21 Kuandyk"], lineB: ["Murat 1", "Meirkhan  3", "Mukatay 4", "Kydyraliev 7", "Mamatov 8", "Omarov 9", "Sadyk 10", "Saparkhan 11", "Senalov 17", "Suyunov 21"], infoA: ["Z.Nurtuganov", "Z.Nurtuganov", "", "", "", "A.Ongarbay", "Z.Nurtuganov", "S.Torehanov(OG)", "D.Khametov", "B.Gazizov", "Z.Nurtuganov"], infoB: ["", "", "B.Ibrahim", "B.Kobilan", "Z.Nakypbek", "", "", "", "", "", ""]),
        Games.init(firstLabel: "Teachers", firstImage: UIImage(named: "Teachers")!, middleLabel: "2:0", secondImage: UIImage(named: "Rizo")!, secondLabel: "Rizo", lineA: ["1 Tangirkul", "3 Yerkeshov", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Urmanov 1", "Yerkinbek  3", "Zhumashev 4", "Mussin 7", "Kokenov 8", "Gotye 9", "Ulanov 10", "Sapargali 11", "Kabi 17", "Kenes 21"], infoA: ["Z.Agybai", "S.Vankeyev"], infoB: ["", ""]),
        Games.init(firstLabel: "Avangar", firstImage: UIImage(named: "Avangar")!, middleLabel: "1:2", secondImage: UIImage(named: "Barabar")!, secondLabel: "Barabar", lineA: ["1 Kuanysh", "3 Sagyngaly", "4 Azamat", "7 Kupesov", "8 Beibit", "9 Ospanov", "10 Imangazin", "11 Makhmutov", "17 Inkar", "21 Agmanov"], lineB: ["Zheksengaliev 1", "Ozhanov 3", "Nurtazayev 4", "Kanatov 7", "Kenzhebulatov 8", "Shah 9", "Zhumabekov 10", "Utarbaev 11", "Tagayev 17", "Serikov 21"], infoA: ["", "", "S.Azamat"], infoB: ["A.Temirbolat", "A.Temirbolat", ""]),
        Games.init(firstLabel: "Nation Army", firstImage: UIImage(named: "Nation Army")!, middleLabel: "0:2", secondImage: UIImage(named: "Alash")!, secondLabel: "Alash", lineA: ["1 Nurpeis", "3 Muratuly", "4 Muratkhan", "7 Otep", "8 Sabitov", "9 Kessikbayev", "10 Irisbayev", "11 Ganshin", "17 Bolatay", "21 Demenov"], lineB: ["Maratov 1", "Zhailybai  3", "Alibekov 4", "Begimbetov 7", "Zhekeev 8", "Bigaliev 9", "Djabasov 10", "Shukatov 11", "Nurpoldin 17", "Zholdin 21"], infoA: ["", ""], infoB: ["M.Seitov", "M.Seitov"]),
        Games.init(firstLabel: "Leicester", firstImage: UIImage(named: "Leicester")!, middleLabel: "2:0", secondImage: UIImage(named: "Antihype")!, secondLabel: "Antihype", lineA: ["1 Kokenov", "5 Muslim", "6 Zhiembay", "8 Saynov", "8 Sagyndyk", "9 Ospanov", "10 Zhapay", "16 Omirzak"], lineB: ["1 Zangar", "4 Abuov", "7 Islamkhan", "8 Alisher", "9 Akhmetov", "17 Merei", "21 Kuanov", "22 Orazaly"], infoA: ["N.Zhiembay", "S.Omirzak"], infoB: ["", ""]),
        Games.init(firstLabel: "Sunkar", firstImage: UIImage(named: "Sunkar")!, middleLabel: "4:1", secondImage: UIImage(named: "Nomad JR")!, secondLabel: "Nomad JR", lineA: ["1 Tashenov", "3 Askhat", "4 Kalilulin", "7 Tursynbaev", "8 Ali", "9 Otep", "10 Roma", "11 Kama", "17 Bolat", "21 Sharapov"], lineB: ["Balkhisov 1", "Rinatov  3", "Guzalin 4", "Kolesnik 7", "Smailov 8", "Kanatbekuly 9", "Sagaladinov 10", "Lesbek 11", "Zhasan 17", "Makat 21"], infoA: ["", "Z.Amangeldeyev", "B.Erkhanov", "E.Izbergen", "F.Batyrkhan"], infoB: ["D.Amirkhanov", "", "", "", ""]),
        
        Games.init(firstLabel: "Kentau", firstImage: UIImage(named: "Kentau")!, middleLabel: "2:2", secondImage: UIImage(named: "Evolution")!, secondLabel: "Evolution", lineA: ["1 Alpamys", "3 Ayagan", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Bairamov 1", "Bekzat  3", "Berdikul 4", "Bissen 7", "Bissenbayev 8", "Sungkar 9", "Gizatov 10", "Maksatov 11", "Danabaev 17", "Kalekes 21"], infoA: ["B.Omarbek", "", "", "B.Asangali"], infoB: ["", "A.Aman", "A.Abaidullin", ""]),
        Games.init(firstLabel: "Sparta", firstImage: UIImage(named: "Sparta")!, middleLabel: "8:3", secondImage: UIImage(named: "Nomad")!, secondLabel: "Nomad", lineA: ["1 Ordabek", "3 Irisbayev", "4 Kokenov", "7 Bektemir", "8 Orman", "9 Ashirkhan", "10 Khametov", "11 Kemelkhan", "17 Khassen", "21 Kuandyk"], lineB: ["Murat 1", "Meirkhan  3", "Mukatay 4", "Kydyraliev 7", "Mamatov 8", "Omarov 9", "Sadyk 10", "Saparkhan 11", "Senalov 17", "Suyunov 21"], infoA: ["Z.Nurtuganov", "Z.Nurtuganov", "", "", "", "A.Ongarbay", "Z.Nurtuganov", "S.Torehanov(OG)", "D.Khametov", "B.Gazizov", "Z.Nurtuganov"], infoB: ["", "", "B.Ibrahim", "B.Kobilan", "Z.Nakypbek", "", "", "", "", "", ""]),
        Games.init(firstLabel: "Teachers", firstImage: UIImage(named: "Teachers")!, middleLabel: "2:0", secondImage: UIImage(named: "Rizo")!, secondLabel: "Rizo", lineA: ["1 Tangirkul", "3 Yerkeshov", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Urmanov 1", "Yerkinbek  3", "Zhumashev 4", "Mussin 7", "Kokenov 8", "Gotye 9", "Ulanov 10", "Sapargali 11", "Kabi 17", "Kenes 21"], infoA: ["Z.Agybai", "S.Vankeyev"], infoB: ["", ""]),
        Games.init(firstLabel: "Avangar", firstImage: UIImage(named: "Avangar")!, middleLabel: "1:2", secondImage: UIImage(named: "Barabar")!, secondLabel: "Barabar", lineA: ["1 Kuanysh", "3 Sagyngaly", "4 Azamat", "7 Kupesov", "8 Beibit", "9 Ospanov", "10 Imangazin", "11 Makhmutov", "17 Inkar", "21 Agmanov"], lineB: ["Zheksengaliev 1", "Ozhanov 3", "Nurtazayev 4", "Kanatov 7", "Kenzhebulatov 8", "Shah 9", "Zhumabekov 10", "Utarbaev 11", "Tagayev 17", "Serikov 21"], infoA: ["", "", "S.Azamat"], infoB: ["A.Temirbolat", "A.Temirbolat", ""]),
        Games.init(firstLabel: "Nation Army", firstImage: UIImage(named: "Nation Army")!, middleLabel: "0:2", secondImage: UIImage(named: "Alash")!, secondLabel: "Alash", lineA: ["1 Nurpeis", "3 Muratuly", "4 Muratkhan", "7 Otep", "8 Sabitov", "9 Kessikbayev", "10 Irisbayev", "11 Ganshin", "17 Bolatay", "21 Demenov"], lineB: ["Maratov 1", "Zhailybai  3", "Alibekov 4", "Begimbetov 7", "Zhekeev 8", "Bigaliev 9", "Djabasov 10", "Shukatov 11", "Nurpoldin 17", "Zholdin 21"], infoA: ["", ""], infoB: ["M.Seitov", "M.Seitov"]),
        Games.init(firstLabel: "Leicester", firstImage: UIImage(named: "Leicester")!, middleLabel: "2:0", secondImage: UIImage(named: "Antihype")!, secondLabel: "Antihype", lineA: ["1 Kokenov", "5 Muslim", "6 Zhiembay", "8 Saynov", "8 Sagyndyk", "9 Ospanov", "10 Zhapay", "16 Omirzak"], lineB: ["1 Zangar", "4 Abuov", "7 Islamkhan", "8 Alisher", "9 Akhmetov", "17 Merei", "21 Kuanov", "22 Orazaly"], infoA: ["N.Zhiembay", "S.Omirzak"], infoB: ["", ""]),
        Games.init(firstLabel: "Sunkar", firstImage: UIImage(named: "Sunkar")!, middleLabel: "4:1", secondImage: UIImage(named: "Nomad JR")!, secondLabel: "Nomad JR", lineA: ["1 Tashenov", "3 Askhat", "4 Kalilulin", "7 Tursynbaev", "8 Ali", "9 Otep", "10 Roma", "11 Kama", "17 Bolat", "21 Sharapov"], lineB: ["Balkhisov 1", "Rinatov  3", "Guzalin 4", "Kolesnik 7", "Smailov 8", "Kanatbekuly 9", "Sagaladinov 10", "Lesbek 11", "Zhasan 17", "Makat 21"], infoA: ["", "Z.Amangeldeyev", "B.Erkhanov", "E.Izbergen", "F.Batyrkhan"], infoB: ["D.Amirkhanov", "", "", "", ""]),
        
        Games.init(firstLabel: "Kentau", firstImage: UIImage(named: "Kentau")!, middleLabel: "2:2", secondImage: UIImage(named: "Evolution")!, secondLabel: "Evolution", lineA: ["1 Alpamys", "3 Ayagan", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Bairamov 1", "Bekzat  3", "Berdikul 4", "Bissen 7", "Bissenbayev 8", "Sungkar 9", "Gizatov 10", "Maksatov 11", "Danabaev 17", "Kalekes 21"], infoA: ["B.Omarbek", "", "", "B.Asangali"], infoB: ["", "A.Aman", "A.Abaidullin", ""]),
        Games.init(firstLabel: "Sparta", firstImage: UIImage(named: "Sparta")!, middleLabel: "8:3", secondImage: UIImage(named: "Nomad")!, secondLabel: "Nomad", lineA: ["1 Ordabek", "3 Irisbayev", "4 Kokenov", "7 Bektemir", "8 Orman", "9 Ashirkhan", "10 Khametov", "11 Kemelkhan", "17 Khassen", "21 Kuandyk"], lineB: ["Murat 1", "Meirkhan  3", "Mukatay 4", "Kydyraliev 7", "Mamatov 8", "Omarov 9", "Sadyk 10", "Saparkhan 11", "Senalov 17", "Suyunov 21"], infoA: ["Z.Nurtuganov", "Z.Nurtuganov", "", "", "", "A.Ongarbay", "Z.Nurtuganov", "S.Torehanov(OG)", "D.Khametov", "B.Gazizov", "Z.Nurtuganov"], infoB: ["", "", "B.Ibrahim", "B.Kobilan", "Z.Nakypbek", "", "", "", "", "", ""]),
        Games.init(firstLabel: "Teachers", firstImage: UIImage(named: "Teachers")!, middleLabel: "2:0", secondImage: UIImage(named: "Rizo")!, secondLabel: "Rizo", lineA: ["1 Tangirkul", "3 Yerkeshov", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Urmanov 1", "Yerkinbek  3", "Zhumashev 4", "Mussin 7", "Kokenov 8", "Gotye 9", "Ulanov 10", "Sapargali 11", "Kabi 17", "Kenes 21"], infoA: ["Z.Agybai", "S.Vankeyev"], infoB: ["", ""]),
        Games.init(firstLabel: "Avangar", firstImage: UIImage(named: "Avangar")!, middleLabel: "1:2", secondImage: UIImage(named: "Barabar")!, secondLabel: "Barabar", lineA: ["1 Kuanysh", "3 Sagyngaly", "4 Azamat", "7 Kupesov", "8 Beibit", "9 Ospanov", "10 Imangazin", "11 Makhmutov", "17 Inkar", "21 Agmanov"], lineB: ["Zheksengaliev 1", "Ozhanov 3", "Nurtazayev 4", "Kanatov 7", "Kenzhebulatov 8", "Shah 9", "Zhumabekov 10", "Utarbaev 11", "Tagayev 17", "Serikov 21"], infoA: ["", "", "S.Azamat"], infoB: ["A.Temirbolat", "A.Temirbolat", ""]),
        Games.init(firstLabel: "Nation Army", firstImage: UIImage(named: "Nation Army")!, middleLabel: "0:2", secondImage: UIImage(named: "Alash")!, secondLabel: "Alash", lineA: ["1 Nurpeis", "3 Muratuly", "4 Muratkhan", "7 Otep", "8 Sabitov", "9 Kessikbayev", "10 Irisbayev", "11 Ganshin", "17 Bolatay", "21 Demenov"], lineB: ["Maratov 1", "Zhailybai  3", "Alibekov 4", "Begimbetov 7", "Zhekeev 8", "Bigaliev 9", "Djabasov 10", "Shukatov 11", "Nurpoldin 17", "Zholdin 21"], infoA: ["", ""], infoB: ["M.Seitov", "M.Seitov"]),
        Games.init(firstLabel: "Leicester", firstImage: UIImage(named: "Leicester")!, middleLabel: "2:0", secondImage: UIImage(named: "Antihype")!, secondLabel: "Antihype", lineA: ["1 Kokenov", "5 Muslim", "6 Zhiembay", "8 Saynov", "8 Sagyndyk", "9 Ospanov", "10 Zhapay", "16 Omirzak"], lineB: ["1 Zangar", "4 Abuov", "7 Islamkhan", "8 Alisher", "9 Akhmetov", "17 Merei", "21 Kuanov", "22 Orazaly"], infoA: ["N.Zhiembay", "S.Omirzak"], infoB: ["", ""]),
        Games.init(firstLabel: "Sunkar", firstImage: UIImage(named: "Sunkar")!, middleLabel: "4:1", secondImage: UIImage(named: "Nomad JR")!, secondLabel: "Nomad JR", lineA: ["1 Tashenov", "3 Askhat", "4 Kalilulin", "7 Tursynbaev", "8 Ali", "9 Otep", "10 Roma", "11 Kama", "17 Bolat", "21 Sharapov"], lineB: ["Balkhisov 1", "Rinatov  3", "Guzalin 4", "Kolesnik 7", "Smailov 8", "Kanatbekuly 9", "Sagaladinov 10", "Lesbek 11", "Zhasan 17", "Makat 21"], infoA: ["", "Z.Amangeldeyev", "B.Erkhanov", "E.Izbergen", "F.Batyrkhan"], infoB: ["D.Amirkhanov", "", "", "", ""]),
        
        Games.init(firstLabel: "Kentau", firstImage: UIImage(named: "Kentau")!, middleLabel: "2:2", secondImage: UIImage(named: "Evolution")!, secondLabel: "Evolution", lineA: ["1 Alpamys", "3 Ayagan", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Bairamov 1", "Bekzat  3", "Berdikul 4", "Bissen 7", "Bissenbayev 8", "Sungkar 9", "Gizatov 10", "Maksatov 11", "Danabaev 17", "Kalekes 21"], infoA: ["B.Omarbek", "", "", "B.Asangali"], infoB: ["", "A.Aman", "A.Abaidullin", ""]),
        Games.init(firstLabel: "Sparta", firstImage: UIImage(named: "Sparta")!, middleLabel: "8:3", secondImage: UIImage(named: "Nomad")!, secondLabel: "Nomad", lineA: ["1 Ordabek", "3 Irisbayev", "4 Kokenov", "7 Bektemir", "8 Orman", "9 Ashirkhan", "10 Khametov", "11 Kemelkhan", "17 Khassen", "21 Kuandyk"], lineB: ["Murat 1", "Meirkhan  3", "Mukatay 4", "Kydyraliev 7", "Mamatov 8", "Omarov 9", "Sadyk 10", "Saparkhan 11", "Senalov 17", "Suyunov 21"], infoA: ["Z.Nurtuganov", "Z.Nurtuganov", "", "", "", "A.Ongarbay", "Z.Nurtuganov", "S.Torehanov(OG)", "D.Khametov", "B.Gazizov", "Z.Nurtuganov"], infoB: ["", "", "B.Ibrahim", "B.Kobilan", "Z.Nakypbek", "", "", "", "", "", ""]),
        Games.init(firstLabel: "Teachers", firstImage: UIImage(named: "Teachers")!, middleLabel: "2:0", secondImage: UIImage(named: "Rizo")!, secondLabel: "Rizo", lineA: ["1 Tangirkul", "3 Yerkeshov", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Urmanov 1", "Yerkinbek  3", "Zhumashev 4", "Mussin 7", "Kokenov 8", "Gotye 9", "Ulanov 10", "Sapargali 11", "Kabi 17", "Kenes 21"], infoA: ["Z.Agybai", "S.Vankeyev"], infoB: ["", ""]),
        Games.init(firstLabel: "Avangar", firstImage: UIImage(named: "Avangar")!, middleLabel: "1:2", secondImage: UIImage(named: "Barabar")!, secondLabel: "Barabar", lineA: ["1 Kuanysh", "3 Sagyngaly", "4 Azamat", "7 Kupesov", "8 Beibit", "9 Ospanov", "10 Imangazin", "11 Makhmutov", "17 Inkar", "21 Agmanov"], lineB: ["Zheksengaliev 1", "Ozhanov 3", "Nurtazayev 4", "Kanatov 7", "Kenzhebulatov 8", "Shah 9", "Zhumabekov 10", "Utarbaev 11", "Tagayev 17", "Serikov 21"], infoA: ["", "", "S.Azamat"], infoB: ["A.Temirbolat", "A.Temirbolat", ""]),
        Games.init(firstLabel: "Nation Army", firstImage: UIImage(named: "Nation Army")!, middleLabel: "0:2", secondImage: UIImage(named: "Alash")!, secondLabel: "Alash", lineA: ["1 Nurpeis", "3 Muratuly", "4 Muratkhan", "7 Otep", "8 Sabitov", "9 Kessikbayev", "10 Irisbayev", "11 Ganshin", "17 Bolatay", "21 Demenov"], lineB: ["Maratov 1", "Zhailybai  3", "Alibekov 4", "Begimbetov 7", "Zhekeev 8", "Bigaliev 9", "Djabasov 10", "Shukatov 11", "Nurpoldin 17", "Zholdin 21"], infoA: ["", ""], infoB: ["M.Seitov", "M.Seitov"]),
        Games.init(firstLabel: "Leicester", firstImage: UIImage(named: "Leicester")!, middleLabel: "2:0", secondImage: UIImage(named: "Antihype")!, secondLabel: "Antihype", lineA: ["1 Kokenov", "5 Muslim", "6 Zhiembay", "8 Saynov", "8 Sagyndyk", "9 Ospanov", "10 Zhapay", "16 Omirzak"], lineB: ["1 Zangar", "4 Abuov", "7 Islamkhan", "8 Alisher", "9 Akhmetov", "17 Merei", "21 Kuanov", "22 Orazaly"], infoA: ["N.Zhiembay", "S.Omirzak"], infoB: ["", ""]),
        Games.init(firstLabel: "Sunkar", firstImage: UIImage(named: "Sunkar")!, middleLabel: "4:1", secondImage: UIImage(named: "Nomad JR")!, secondLabel: "Nomad JR", lineA: ["1 Tashenov", "3 Askhat", "4 Kalilulin", "7 Tursynbaev", "8 Ali", "9 Otep", "10 Roma", "11 Kama", "17 Bolat", "21 Sharapov"], lineB: ["Balkhisov 1", "Rinatov  3", "Guzalin 4", "Kolesnik 7", "Smailov 8", "Kanatbekuly 9", "Sagaladinov 10", "Lesbek 11", "Zhasan 17", "Makat 21"], infoA: ["", "Z.Amangeldeyev", "B.Erkhanov", "E.Izbergen", "F.Batyrkhan"], infoB: ["D.Amirkhanov", "", "", "", ""]),
        
        Games.init(firstLabel: "Kentau", firstImage: UIImage(named: "Kentau")!, middleLabel: "2:2", secondImage: UIImage(named: "Evolution")!, secondLabel: "Evolution", lineA: ["1 Alpamys", "3 Ayagan", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Bairamov 1", "Bekzat  3", "Berdikul 4", "Bissen 7", "Bissenbayev 8", "Sungkar 9", "Gizatov 10", "Maksatov 11", "Danabaev 17", "Kalekes 21"], infoA: ["B.Omarbek", "", "", "B.Asangali"], infoB: ["", "A.Aman", "A.Abaidullin", ""]),
        Games.init(firstLabel: "Sparta", firstImage: UIImage(named: "Sparta")!, middleLabel: "8:3", secondImage: UIImage(named: "Nomad")!, secondLabel: "Nomad", lineA: ["1 Ordabek", "3 Irisbayev", "4 Kokenov", "7 Bektemir", "8 Orman", "9 Ashirkhan", "10 Khametov", "11 Kemelkhan", "17 Khassen", "21 Kuandyk"], lineB: ["Murat 1", "Meirkhan  3", "Mukatay 4", "Kydyraliev 7", "Mamatov 8", "Omarov 9", "Sadyk 10", "Saparkhan 11", "Senalov 17", "Suyunov 21"], infoA: ["Z.Nurtuganov", "Z.Nurtuganov", "", "", "", "A.Ongarbay", "Z.Nurtuganov", "S.Torehanov(OG)", "D.Khametov", "B.Gazizov", "Z.Nurtuganov"], infoB: ["", "", "B.Ibrahim", "B.Kobilan", "Z.Nakypbek", "", "", "", "", "", ""]),
        Games.init(firstLabel: "Teachers", firstImage: UIImage(named: "Teachers")!, middleLabel: "2:0", secondImage: UIImage(named: "Rizo")!, secondLabel: "Rizo", lineA: ["1 Tangirkul", "3 Yerkeshov", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Urmanov 1", "Yerkinbek  3", "Zhumashev 4", "Mussin 7", "Kokenov 8", "Gotye 9", "Ulanov 10", "Sapargali 11", "Kabi 17", "Kenes 21"], infoA: ["Z.Agybai", "S.Vankeyev"], infoB: ["", ""]),
        Games.init(firstLabel: "Avangar", firstImage: UIImage(named: "Avangar")!, middleLabel: "1:2", secondImage: UIImage(named: "Barabar")!, secondLabel: "Barabar", lineA: ["1 Kuanysh", "3 Sagyngaly", "4 Azamat", "7 Kupesov", "8 Beibit", "9 Ospanov", "10 Imangazin", "11 Makhmutov", "17 Inkar", "21 Agmanov"], lineB: ["Zheksengaliev 1", "Ozhanov 3", "Nurtazayev 4", "Kanatov 7", "Kenzhebulatov 8", "Shah 9", "Zhumabekov 10", "Utarbaev 11", "Tagayev 17", "Serikov 21"], infoA: ["", "", "S.Azamat"], infoB: ["A.Temirbolat", "A.Temirbolat", ""]),
        Games.init(firstLabel: "Nation Army", firstImage: UIImage(named: "Nation Army")!, middleLabel: "0:2", secondImage: UIImage(named: "Alash")!, secondLabel: "Alash", lineA: ["1 Nurpeis", "3 Muratuly", "4 Muratkhan", "7 Otep", "8 Sabitov", "9 Kessikbayev", "10 Irisbayev", "11 Ganshin", "17 Bolatay", "21 Demenov"], lineB: ["Maratov 1", "Zhailybai  3", "Alibekov 4", "Begimbetov 7", "Zhekeev 8", "Bigaliev 9", "Djabasov 10", "Shukatov 11", "Nurpoldin 17", "Zholdin 21"], infoA: ["", ""], infoB: ["M.Seitov", "M.Seitov"]),
        Games.init(firstLabel: "Leicester", firstImage: UIImage(named: "Leicester")!, middleLabel: "2:0", secondImage: UIImage(named: "Antihype")!, secondLabel: "Antihype", lineA: ["1 Kokenov", "5 Muslim", "6 Zhiembay", "8 Saynov", "8 Sagyndyk", "9 Ospanov", "10 Zhapay", "16 Omirzak"], lineB: ["1 Zangar", "4 Abuov", "7 Islamkhan", "8 Alisher", "9 Akhmetov", "17 Merei", "21 Kuanov", "22 Orazaly"], infoA: ["N.Zhiembay", "S.Omirzak"], infoB: ["", ""]),
        Games.init(firstLabel: "Sunkar", firstImage: UIImage(named: "Sunkar")!, middleLabel: "4:1", secondImage: UIImage(named: "Nomad JR")!, secondLabel: "Nomad JR", lineA: ["1 Tashenov", "3 Askhat", "4 Kalilulin", "7 Tursynbaev", "8 Ali", "9 Otep", "10 Roma", "11 Kama", "17 Bolat", "21 Sharapov"], lineB: ["Balkhisov 1", "Rinatov  3", "Guzalin 4", "Kolesnik 7", "Smailov 8", "Kanatbekuly 9", "Sagaladinov 10", "Lesbek 11", "Zhasan 17", "Makat 21"], infoA: ["", "Z.Amangeldeyev", "B.Erkhanov", "E.Izbergen", "F.Batyrkhan"], infoB: ["D.Amirkhanov", "", "", "", ""]),
        
        Games.init(firstLabel: "Kentau", firstImage: UIImage(named: "Kentau")!, middleLabel: "2:2", secondImage: UIImage(named: "Evolution")!, secondLabel: "Evolution", lineA: ["1 Alpamys", "3 Ayagan", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Bairamov 1", "Bekzat  3", "Berdikul 4", "Bissen 7", "Bissenbayev 8", "Sungkar 9", "Gizatov 10", "Maksatov 11", "Danabaev 17", "Kalekes 21"], infoA: ["B.Omarbek", "", "", "B.Asangali"], infoB: ["", "A.Aman", "A.Abaidullin", ""]),
        Games.init(firstLabel: "Sparta", firstImage: UIImage(named: "Sparta")!, middleLabel: "8:3", secondImage: UIImage(named: "Nomad")!, secondLabel: "Nomad", lineA: ["1 Ordabek", "3 Irisbayev", "4 Kokenov", "7 Bektemir", "8 Orman", "9 Ashirkhan", "10 Khametov", "11 Kemelkhan", "17 Khassen", "21 Kuandyk"], lineB: ["Murat 1", "Meirkhan  3", "Mukatay 4", "Kydyraliev 7", "Mamatov 8", "Omarov 9", "Sadyk 10", "Saparkhan 11", "Senalov 17", "Suyunov 21"], infoA: ["Z.Nurtuganov", "Z.Nurtuganov", "", "", "", "A.Ongarbay", "Z.Nurtuganov", "S.Torehanov(OG)", "D.Khametov", "B.Gazizov", "Z.Nurtuganov"], infoB: ["", "", "B.Ibrahim", "B.Kobilan", "Z.Nakypbek", "", "", "", "", "", ""]),
        Games.init(firstLabel: "Teachers", firstImage: UIImage(named: "Teachers")!, middleLabel: "2:0", secondImage: UIImage(named: "Rizo")!, secondLabel: "Rizo", lineA: ["1 Tangirkul", "3 Yerkeshov", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Urmanov 1", "Yerkinbek  3", "Zhumashev 4", "Mussin 7", "Kokenov 8", "Gotye 9", "Ulanov 10", "Sapargali 11", "Kabi 17", "Kenes 21"], infoA: ["Z.Agybai", "S.Vankeyev"], infoB: ["", ""]),
        Games.init(firstLabel: "Avangar", firstImage: UIImage(named: "Avangar")!, middleLabel: "1:2", secondImage: UIImage(named: "Barabar")!, secondLabel: "Barabar", lineA: ["1 Kuanysh", "3 Sagyngaly", "4 Azamat", "7 Kupesov", "8 Beibit", "9 Ospanov", "10 Imangazin", "11 Makhmutov", "17 Inkar", "21 Agmanov"], lineB: ["Zheksengaliev 1", "Ozhanov 3", "Nurtazayev 4", "Kanatov 7", "Kenzhebulatov 8", "Shah 9", "Zhumabekov 10", "Utarbaev 11", "Tagayev 17", "Serikov 21"], infoA: ["", "", "S.Azamat"], infoB: ["A.Temirbolat", "A.Temirbolat", ""]),
        Games.init(firstLabel: "Nation Army", firstImage: UIImage(named: "Nation Army")!, middleLabel: "0:2", secondImage: UIImage(named: "Alash")!, secondLabel: "Alash", lineA: ["1 Nurpeis", "3 Muratuly", "4 Muratkhan", "7 Otep", "8 Sabitov", "9 Kessikbayev", "10 Irisbayev", "11 Ganshin", "17 Bolatay", "21 Demenov"], lineB: ["Maratov 1", "Zhailybai  3", "Alibekov 4", "Begimbetov 7", "Zhekeev 8", "Bigaliev 9", "Djabasov 10", "Shukatov 11", "Nurpoldin 17", "Zholdin 21"], infoA: ["", ""], infoB: ["M.Seitov", "M.Seitov"]),
        Games.init(firstLabel: "Leicester", firstImage: UIImage(named: "Leicester")!, middleLabel: "2:0", secondImage: UIImage(named: "Antihype")!, secondLabel: "Antihype", lineA: ["1 Kokenov", "5 Muslim", "6 Zhiembay", "8 Saynov", "8 Sagyndyk", "9 Ospanov", "10 Zhapay", "16 Omirzak"], lineB: ["1 Zangar", "4 Abuov", "7 Islamkhan", "8 Alisher", "9 Akhmetov", "17 Merei", "21 Kuanov", "22 Orazaly"], infoA: ["N.Zhiembay", "S.Omirzak"], infoB: ["", ""]),
        Games.init(firstLabel: "Sunkar", firstImage: UIImage(named: "Sunkar")!, middleLabel: "4:1", secondImage: UIImage(named: "Nomad JR")!, secondLabel: "Nomad JR", lineA: ["1 Tashenov", "3 Askhat", "4 Kalilulin", "7 Tursynbaev", "8 Ali", "9 Otep", "10 Roma", "11 Kama", "17 Bolat", "21 Sharapov"], lineB: ["Balkhisov 1", "Rinatov  3", "Guzalin 4", "Kolesnik 7", "Smailov 8", "Kanatbekuly 9", "Sagaladinov 10", "Lesbek 11", "Zhasan 17", "Makat 21"], infoA: ["", "Z.Amangeldeyev", "B.Erkhanov", "E.Izbergen", "F.Batyrkhan"], infoB: ["D.Amirkhanov", "", "", "", ""]),
        
        Games.init(firstLabel: "Kentau", firstImage: UIImage(named: "Kentau")!, middleLabel: "2:2", secondImage: UIImage(named: "Evolution")!, secondLabel: "Evolution", lineA: ["1 Alpamys", "3 Ayagan", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Bairamov 1", "Bekzat  3", "Berdikul 4", "Bissen 7", "Bissenbayev 8", "Sungkar 9", "Gizatov 10", "Maksatov 11", "Danabaev 17", "Kalekes 21"], infoA: ["B.Omarbek", "", "", "B.Asangali"], infoB: ["", "A.Aman", "A.Abaidullin", ""]),
        Games.init(firstLabel: "Sparta", firstImage: UIImage(named: "Sparta")!, middleLabel: "8:3", secondImage: UIImage(named: "Nomad")!, secondLabel: "Nomad", lineA: ["1 Ordabek", "3 Irisbayev", "4 Kokenov", "7 Bektemir", "8 Orman", "9 Ashirkhan", "10 Khametov", "11 Kemelkhan", "17 Khassen", "21 Kuandyk"], lineB: ["Murat 1", "Meirkhan  3", "Mukatay 4", "Kydyraliev 7", "Mamatov 8", "Omarov 9", "Sadyk 10", "Saparkhan 11", "Senalov 17", "Suyunov 21"], infoA: ["Z.Nurtuganov", "Z.Nurtuganov", "", "", "", "A.Ongarbay", "Z.Nurtuganov", "S.Torehanov(OG)", "D.Khametov", "B.Gazizov", "Z.Nurtuganov"], infoB: ["", "", "B.Ibrahim", "B.Kobilan", "Z.Nakypbek", "", "", "", "", "", ""]),
        Games.init(firstLabel: "Teachers", firstImage: UIImage(named: "Teachers")!, middleLabel: "2:0", secondImage: UIImage(named: "Rizo")!, secondLabel: "Rizo", lineA: ["1 Tangirkul", "3 Yerkeshov", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Urmanov 1", "Yerkinbek  3", "Zhumashev 4", "Mussin 7", "Kokenov 8", "Gotye 9", "Ulanov 10", "Sapargali 11", "Kabi 17", "Kenes 21"], infoA: ["Z.Agybai", "S.Vankeyev"], infoB: ["", ""]),
        Games.init(firstLabel: "Avangar", firstImage: UIImage(named: "Avangar")!, middleLabel: "1:2", secondImage: UIImage(named: "Barabar")!, secondLabel: "Barabar", lineA: ["1 Kuanysh", "3 Sagyngaly", "4 Azamat", "7 Kupesov", "8 Beibit", "9 Ospanov", "10 Imangazin", "11 Makhmutov", "17 Inkar", "21 Agmanov"], lineB: ["Zheksengaliev 1", "Ozhanov 3", "Nurtazayev 4", "Kanatov 7", "Kenzhebulatov 8", "Shah 9", "Zhumabekov 10", "Utarbaev 11", "Tagayev 17", "Serikov 21"], infoA: ["", "", "S.Azamat"], infoB: ["A.Temirbolat", "A.Temirbolat", ""]),
        Games.init(firstLabel: "Nation Army", firstImage: UIImage(named: "Nation Army")!, middleLabel: "0:2", secondImage: UIImage(named: "Alash")!, secondLabel: "Alash", lineA: ["1 Nurpeis", "3 Muratuly", "4 Muratkhan", "7 Otep", "8 Sabitov", "9 Kessikbayev", "10 Irisbayev", "11 Ganshin", "17 Bolatay", "21 Demenov"], lineB: ["Maratov 1", "Zhailybai  3", "Alibekov 4", "Begimbetov 7", "Zhekeev 8", "Bigaliev 9", "Djabasov 10", "Shukatov 11", "Nurpoldin 17", "Zholdin 21"], infoA: ["", ""], infoB: ["M.Seitov", "M.Seitov"]),
        Games.init(firstLabel: "Leicester", firstImage: UIImage(named: "Leicester")!, middleLabel: "2:0", secondImage: UIImage(named: "Antihype")!, secondLabel: "Antihype", lineA: ["1 Kokenov", "5 Muslim", "6 Zhiembay", "8 Saynov", "8 Sagyndyk", "9 Ospanov", "10 Zhapay", "16 Omirzak"], lineB: ["1 Zangar", "4 Abuov", "7 Islamkhan", "8 Alisher", "9 Akhmetov", "17 Merei", "21 Kuanov", "22 Orazaly"], infoA: ["N.Zhiembay", "S.Omirzak"], infoB: ["", ""]),
        Games.init(firstLabel: "Sunkar", firstImage: UIImage(named: "Sunkar")!, middleLabel: "4:1", secondImage: UIImage(named: "Nomad JR")!, secondLabel: "Nomad JR", lineA: ["1 Tashenov", "3 Askhat", "4 Kalilulin", "7 Tursynbaev", "8 Ali", "9 Otep", "10 Roma", "11 Kama", "17 Bolat", "21 Sharapov"], lineB: ["Balkhisov 1", "Rinatov  3", "Guzalin 4", "Kolesnik 7", "Smailov 8", "Kanatbekuly 9", "Sagaladinov 10", "Lesbek 11", "Zhasan 17", "Makat 21"], infoA: ["", "Z.Amangeldeyev", "B.Erkhanov", "E.Izbergen", "F.Batyrkhan"], infoB: ["D.Amirkhanov", "", "", "", ""]),
        
        Games.init(firstLabel: "Kentau", firstImage: UIImage(named: "Kentau")!, middleLabel: "2:2", secondImage: UIImage(named: "Evolution")!, secondLabel: "Evolution", lineA: ["1 Alpamys", "3 Ayagan", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Bairamov 1", "Bekzat  3", "Berdikul 4", "Bissen 7", "Bissenbayev 8", "Sungkar 9", "Gizatov 10", "Maksatov 11", "Danabaev 17", "Kalekes 21"], infoA: ["B.Omarbek", "", "", "B.Asangali"], infoB: ["", "A.Aman", "A.Abaidullin", ""]),
        Games.init(firstLabel: "Sparta", firstImage: UIImage(named: "Sparta")!, middleLabel: "8:3", secondImage: UIImage(named: "Nomad")!, secondLabel: "Nomad", lineA: ["1 Ordabek", "3 Irisbayev", "4 Kokenov", "7 Bektemir", "8 Orman", "9 Ashirkhan", "10 Khametov", "11 Kemelkhan", "17 Khassen", "21 Kuandyk"], lineB: ["Murat 1", "Meirkhan  3", "Mukatay 4", "Kydyraliev 7", "Mamatov 8", "Omarov 9", "Sadyk 10", "Saparkhan 11", "Senalov 17", "Suyunov 21"], infoA: ["Z.Nurtuganov", "Z.Nurtuganov", "", "", "", "A.Ongarbay", "Z.Nurtuganov", "S.Torehanov(OG)", "D.Khametov", "B.Gazizov", "Z.Nurtuganov"], infoB: ["", "", "B.Ibrahim", "B.Kobilan", "Z.Nakypbek", "", "", "", "", "", ""]),
        Games.init(firstLabel: "Teachers", firstImage: UIImage(named: "Teachers")!, middleLabel: "2:0", secondImage: UIImage(named: "Rizo")!, secondLabel: "Rizo", lineA: ["1 Tangirkul", "3 Yerkeshov", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Urmanov 1", "Yerkinbek  3", "Zhumashev 4", "Mussin 7", "Kokenov 8", "Gotye 9", "Ulanov 10", "Sapargali 11", "Kabi 17", "Kenes 21"], infoA: ["Z.Agybai", "S.Vankeyev"], infoB: ["", ""]),
        Games.init(firstLabel: "Avangar", firstImage: UIImage(named: "Avangar")!, middleLabel: "1:2", secondImage: UIImage(named: "Barabar")!, secondLabel: "Barabar", lineA: ["1 Kuanysh", "3 Sagyngaly", "4 Azamat", "7 Kupesov", "8 Beibit", "9 Ospanov", "10 Imangazin", "11 Makhmutov", "17 Inkar", "21 Agmanov"], lineB: ["Zheksengaliev 1", "Ozhanov 3", "Nurtazayev 4", "Kanatov 7", "Kenzhebulatov 8", "Shah 9", "Zhumabekov 10", "Utarbaev 11", "Tagayev 17", "Serikov 21"], infoA: ["", "", "S.Azamat"], infoB: ["A.Temirbolat", "A.Temirbolat", ""]),
        Games.init(firstLabel: "Nation Army", firstImage: UIImage(named: "Nation Army")!, middleLabel: "0:2", secondImage: UIImage(named: "Alash")!, secondLabel: "Alash", lineA: ["1 Nurpeis", "3 Muratuly", "4 Muratkhan", "7 Otep", "8 Sabitov", "9 Kessikbayev", "10 Irisbayev", "11 Ganshin", "17 Bolatay", "21 Demenov"], lineB: ["Maratov 1", "Zhailybai  3", "Alibekov 4", "Begimbetov 7", "Zhekeev 8", "Bigaliev 9", "Djabasov 10", "Shukatov 11", "Nurpoldin 17", "Zholdin 21"], infoA: ["", ""], infoB: ["M.Seitov", "M.Seitov"]),
        Games.init(firstLabel: "Leicester", firstImage: UIImage(named: "Leicester")!, middleLabel: "2:0", secondImage: UIImage(named: "Antihype")!, secondLabel: "Antihype", lineA: ["1 Kokenov", "5 Muslim", "6 Zhiembay", "8 Saynov", "8 Sagyndyk", "9 Ospanov", "10 Zhapay", "16 Omirzak"], lineB: ["1 Zangar", "4 Abuov", "7 Islamkhan", "8 Alisher", "9 Akhmetov", "17 Merei", "21 Kuanov", "22 Orazaly"], infoA: ["N.Zhiembay", "S.Omirzak"], infoB: ["", ""]),
        Games.init(firstLabel: "Sunkar", firstImage: UIImage(named: "Sunkar")!, middleLabel: "4:1", secondImage: UIImage(named: "Nomad JR")!, secondLabel: "Nomad JR", lineA: ["1 Tashenov", "3 Askhat", "4 Kalilulin", "7 Tursynbaev", "8 Ali", "9 Otep", "10 Roma", "11 Kama", "17 Bolat", "21 Sharapov"], lineB: ["Balkhisov 1", "Rinatov  3", "Guzalin 4", "Kolesnik 7", "Smailov 8", "Kanatbekuly 9", "Sagaladinov 10", "Lesbek 11", "Zhasan 17", "Makat 21"], infoA: ["", "Z.Amangeldeyev", "B.Erkhanov", "E.Izbergen", "F.Batyrkhan"], infoB: ["D.Amirkhanov", "", "", "", ""]),
        
        Games.init(firstLabel: "Kentau", firstImage: UIImage(named: "Kentau")!, middleLabel: "2:2", secondImage: UIImage(named: "Evolution")!, secondLabel: "Evolution", lineA: ["1 Alpamys", "3 Ayagan", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Bairamov 1", "Bekzat  3", "Berdikul 4", "Bissen 7", "Bissenbayev 8", "Sungkar 9", "Gizatov 10", "Maksatov 11", "Danabaev 17", "Kalekes 21"], infoA: ["B.Omarbek", "", "", "B.Asangali"], infoB: ["", "A.Aman", "A.Abaidullin", ""]),
        Games.init(firstLabel: "Sparta", firstImage: UIImage(named: "Sparta")!, middleLabel: "8:3", secondImage: UIImage(named: "Nomad")!, secondLabel: "Nomad", lineA: ["1 Ordabek", "3 Irisbayev", "4 Kokenov", "7 Bektemir", "8 Orman", "9 Ashirkhan", "10 Khametov", "11 Kemelkhan", "17 Khassen", "21 Kuandyk"], lineB: ["Murat 1", "Meirkhan  3", "Mukatay 4", "Kydyraliev 7", "Mamatov 8", "Omarov 9", "Sadyk 10", "Saparkhan 11", "Senalov 17", "Suyunov 21"], infoA: ["Z.Nurtuganov", "Z.Nurtuganov", "", "", "", "A.Ongarbay", "Z.Nurtuganov", "S.Torehanov(OG)", "D.Khametov", "B.Gazizov", "Z.Nurtuganov"], infoB: ["", "", "B.Ibrahim", "B.Kobilan", "Z.Nakypbek", "", "", "", "", "", ""]),
        Games.init(firstLabel: "Teachers", firstImage: UIImage(named: "Teachers")!, middleLabel: "2:0", secondImage: UIImage(named: "Rizo")!, secondLabel: "Rizo", lineA: ["1 Tangirkul", "3 Yerkeshov", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Urmanov 1", "Yerkinbek  3", "Zhumashev 4", "Mussin 7", "Kokenov 8", "Gotye 9", "Ulanov 10", "Sapargali 11", "Kabi 17", "Kenes 21"], infoA: ["Z.Agybai", "S.Vankeyev"], infoB: ["", ""]),
        Games.init(firstLabel: "Avangar", firstImage: UIImage(named: "Avangar")!, middleLabel: "1:2", secondImage: UIImage(named: "Barabar")!, secondLabel: "Barabar", lineA: ["1 Kuanysh", "3 Sagyngaly", "4 Azamat", "7 Kupesov", "8 Beibit", "9 Ospanov", "10 Imangazin", "11 Makhmutov", "17 Inkar", "21 Agmanov"], lineB: ["Zheksengaliev 1", "Ozhanov 3", "Nurtazayev 4", "Kanatov 7", "Kenzhebulatov 8", "Shah 9", "Zhumabekov 10", "Utarbaev 11", "Tagayev 17", "Serikov 21"], infoA: ["", "", "S.Azamat"], infoB: ["A.Temirbolat", "A.Temirbolat", ""]),
        Games.init(firstLabel: "Nation Army", firstImage: UIImage(named: "Nation Army")!, middleLabel: "0:2", secondImage: UIImage(named: "Alash")!, secondLabel: "Alash", lineA: ["1 Nurpeis", "3 Muratuly", "4 Muratkhan", "7 Otep", "8 Sabitov", "9 Kessikbayev", "10 Irisbayev", "11 Ganshin", "17 Bolatay", "21 Demenov"], lineB: ["Maratov 1", "Zhailybai  3", "Alibekov 4", "Begimbetov 7", "Zhekeev 8", "Bigaliev 9", "Djabasov 10", "Shukatov 11", "Nurpoldin 17", "Zholdin 21"], infoA: ["", ""], infoB: ["M.Seitov", "M.Seitov"]),
        Games.init(firstLabel: "Leicester", firstImage: UIImage(named: "Leicester")!, middleLabel: "2:0", secondImage: UIImage(named: "Antihype")!, secondLabel: "Antihype", lineA: ["1 Kokenov", "5 Muslim", "6 Zhiembay", "8 Saynov", "8 Sagyndyk", "9 Ospanov", "10 Zhapay", "16 Omirzak"], lineB: ["1 Zangar", "4 Abuov", "7 Islamkhan", "8 Alisher", "9 Akhmetov", "17 Merei", "21 Kuanov", "22 Orazaly"], infoA: ["N.Zhiembay", "S.Omirzak"], infoB: ["", ""]),
        Games.init(firstLabel: "Sunkar", firstImage: UIImage(named: "Sunkar")!, middleLabel: "4:1", secondImage: UIImage(named: "Nomad JR")!, secondLabel: "Nomad JR", lineA: ["1 Tashenov", "3 Askhat", "4 Kalilulin", "7 Tursynbaev", "8 Ali", "9 Otep", "10 Roma", "11 Kama", "17 Bolat", "21 Sharapov"], lineB: ["Balkhisov 1", "Rinatov  3", "Guzalin 4", "Kolesnik 7", "Smailov 8", "Kanatbekuly 9", "Sagaladinov 10", "Lesbek 11", "Zhasan 17", "Makat 21"], infoA: ["", "Z.Amangeldeyev", "B.Erkhanov", "E.Izbergen", "F.Batyrkhan"], infoB: ["D.Amirkhanov", "", "", "", ""]),
        
        Games.init(firstLabel: "Kentau", firstImage: UIImage(named: "Kentau")!, middleLabel: "2:2", secondImage: UIImage(named: "Evolution")!, secondLabel: "Evolution", lineA: ["1 Alpamys", "3 Ayagan", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Bairamov 1", "Bekzat  3", "Berdikul 4", "Bissen 7", "Bissenbayev 8", "Sungkar 9", "Gizatov 10", "Maksatov 11", "Danabaev 17", "Kalekes 21"], infoA: ["B.Omarbek", "", "", "B.Asangali"], infoB: ["", "A.Aman", "A.Abaidullin", ""]),
        Games.init(firstLabel: "Sparta", firstImage: UIImage(named: "Sparta")!, middleLabel: "8:3", secondImage: UIImage(named: "Nomad")!, secondLabel: "Nomad", lineA: ["1 Ordabek", "3 Irisbayev", "4 Kokenov", "7 Bektemir", "8 Orman", "9 Ashirkhan", "10 Khametov", "11 Kemelkhan", "17 Khassen", "21 Kuandyk"], lineB: ["Murat 1", "Meirkhan  3", "Mukatay 4", "Kydyraliev 7", "Mamatov 8", "Omarov 9", "Sadyk 10", "Saparkhan 11", "Senalov 17", "Suyunov 21"], infoA: ["Z.Nurtuganov", "Z.Nurtuganov", "", "", "", "A.Ongarbay", "Z.Nurtuganov", "S.Torehanov(OG)", "D.Khametov", "B.Gazizov", "Z.Nurtuganov"], infoB: ["", "", "B.Ibrahim", "B.Kobilan", "Z.Nakypbek", "", "", "", "", "", ""]),
        Games.init(firstLabel: "Teachers", firstImage: UIImage(named: "Teachers")!, middleLabel: "2:0", secondImage: UIImage(named: "Rizo")!, secondLabel: "Rizo", lineA: ["1 Tangirkul", "3 Yerkeshov", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Urmanov 1", "Yerkinbek  3", "Zhumashev 4", "Mussin 7", "Kokenov 8", "Gotye 9", "Ulanov 10", "Sapargali 11", "Kabi 17", "Kenes 21"], infoA: ["Z.Agybai", "S.Vankeyev"], infoB: ["", ""]),
        Games.init(firstLabel: "Avangar", firstImage: UIImage(named: "Avangar")!, middleLabel: "1:2", secondImage: UIImage(named: "Barabar")!, secondLabel: "Barabar", lineA: ["1 Kuanysh", "3 Sagyngaly", "4 Azamat", "7 Kupesov", "8 Beibit", "9 Ospanov", "10 Imangazin", "11 Makhmutov", "17 Inkar", "21 Agmanov"], lineB: ["Zheksengaliev 1", "Ozhanov 3", "Nurtazayev 4", "Kanatov 7", "Kenzhebulatov 8", "Shah 9", "Zhumabekov 10", "Utarbaev 11", "Tagayev 17", "Serikov 21"], infoA: ["", "", "S.Azamat"], infoB: ["A.Temirbolat", "A.Temirbolat", ""]),
        Games.init(firstLabel: "Nation Army", firstImage: UIImage(named: "Nation Army")!, middleLabel: "0:2", secondImage: UIImage(named: "Alash")!, secondLabel: "Alash", lineA: ["1 Nurpeis", "3 Muratuly", "4 Muratkhan", "7 Otep", "8 Sabitov", "9 Kessikbayev", "10 Irisbayev", "11 Ganshin", "17 Bolatay", "21 Demenov"], lineB: ["Maratov 1", "Zhailybai  3", "Alibekov 4", "Begimbetov 7", "Zhekeev 8", "Bigaliev 9", "Djabasov 10", "Shukatov 11", "Nurpoldin 17", "Zholdin 21"], infoA: ["", ""], infoB: ["M.Seitov", "M.Seitov"]),
        Games.init(firstLabel: "Leicester", firstImage: UIImage(named: "Leicester")!, middleLabel: "2:0", secondImage: UIImage(named: "Antihype")!, secondLabel: "Antihype", lineA: ["1 Kokenov", "5 Muslim", "6 Zhiembay", "8 Saynov", "8 Sagyndyk", "9 Ospanov", "10 Zhapay", "16 Omirzak"], lineB: ["1 Zangar", "4 Abuov", "7 Islamkhan", "8 Alisher", "9 Akhmetov", "17 Merei", "21 Kuanov", "22 Orazaly"], infoA: ["N.Zhiembay", "S.Omirzak"], infoB: ["", ""]),
        Games.init(firstLabel: "Sunkar", firstImage: UIImage(named: "Sunkar")!, middleLabel: "4:1", secondImage: UIImage(named: "Nomad JR")!, secondLabel: "Nomad JR", lineA: ["1 Tashenov", "3 Askhat", "4 Kalilulin", "7 Tursynbaev", "8 Ali", "9 Otep", "10 Roma", "11 Kama", "17 Bolat", "21 Sharapov"], lineB: ["Balkhisov 1", "Rinatov  3", "Guzalin 4", "Kolesnik 7", "Smailov 8", "Kanatbekuly 9", "Sagaladinov 10", "Lesbek 11", "Zhasan 17", "Makat 21"], infoA: ["", "Z.Amangeldeyev", "B.Erkhanov", "E.Izbergen", "F.Batyrkhan"], infoB: ["D.Amirkhanov", "", "", "", ""]),
        
        Games.init(firstLabel: "Kentau", firstImage: UIImage(named: "Kentau")!, middleLabel: "2:2", secondImage: UIImage(named: "Evolution")!, secondLabel: "Evolution", lineA: ["1 Alpamys", "3 Ayagan", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Bairamov 1", "Bekzat  3", "Berdikul 4", "Bissen 7", "Bissenbayev 8", "Sungkar 9", "Gizatov 10", "Maksatov 11", "Danabaev 17", "Kalekes 21"], infoA: ["B.Omarbek", "", "", "B.Asangali"], infoB: ["", "A.Aman", "A.Abaidullin", ""]),
        Games.init(firstLabel: "Sparta", firstImage: UIImage(named: "Sparta")!, middleLabel: "8:3", secondImage: UIImage(named: "Nomad")!, secondLabel: "Nomad", lineA: ["1 Ordabek", "3 Irisbayev", "4 Kokenov", "7 Bektemir", "8 Orman", "9 Ashirkhan", "10 Khametov", "11 Kemelkhan", "17 Khassen", "21 Kuandyk"], lineB: ["Murat 1", "Meirkhan  3", "Mukatay 4", "Kydyraliev 7", "Mamatov 8", "Omarov 9", "Sadyk 10", "Saparkhan 11", "Senalov 17", "Suyunov 21"], infoA: ["Z.Nurtuganov", "Z.Nurtuganov", "", "", "", "A.Ongarbay", "Z.Nurtuganov", "S.Torehanov(OG)", "D.Khametov", "B.Gazizov", "Z.Nurtuganov"], infoB: ["", "", "B.Ibrahim", "B.Kobilan", "Z.Nakypbek", "", "", "", "", "", ""]),
        Games.init(firstLabel: "Teachers", firstImage: UIImage(named: "Teachers")!, middleLabel: "2:0", secondImage: UIImage(named: "Rizo")!, secondLabel: "Rizo", lineA: ["1 Tangirkul", "3 Yerkeshov", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Urmanov 1", "Yerkinbek  3", "Zhumashev 4", "Mussin 7", "Kokenov 8", "Gotye 9", "Ulanov 10", "Sapargali 11", "Kabi 17", "Kenes 21"], infoA: ["Z.Agybai", "S.Vankeyev"], infoB: ["", ""]),
        Games.init(firstLabel: "Avangar", firstImage: UIImage(named: "Avangar")!, middleLabel: "1:2", secondImage: UIImage(named: "Barabar")!, secondLabel: "Barabar", lineA: ["1 Kuanysh", "3 Sagyngaly", "4 Azamat", "7 Kupesov", "8 Beibit", "9 Ospanov", "10 Imangazin", "11 Makhmutov", "17 Inkar", "21 Agmanov"], lineB: ["Zheksengaliev 1", "Ozhanov 3", "Nurtazayev 4", "Kanatov 7", "Kenzhebulatov 8", "Shah 9", "Zhumabekov 10", "Utarbaev 11", "Tagayev 17", "Serikov 21"], infoA: ["", "", "S.Azamat"], infoB: ["A.Temirbolat", "A.Temirbolat", ""]),
        Games.init(firstLabel: "Nation Army", firstImage: UIImage(named: "Nation Army")!, middleLabel: "0:2", secondImage: UIImage(named: "Alash")!, secondLabel: "Alash", lineA: ["1 Nurpeis", "3 Muratuly", "4 Muratkhan", "7 Otep", "8 Sabitov", "9 Kessikbayev", "10 Irisbayev", "11 Ganshin", "17 Bolatay", "21 Demenov"], lineB: ["Maratov 1", "Zhailybai  3", "Alibekov 4", "Begimbetov 7", "Zhekeev 8", "Bigaliev 9", "Djabasov 10", "Shukatov 11", "Nurpoldin 17", "Zholdin 21"], infoA: ["", ""], infoB: ["M.Seitov", "M.Seitov"]),
        Games.init(firstLabel: "Leicester", firstImage: UIImage(named: "Leicester")!, middleLabel: "2:0", secondImage: UIImage(named: "Antihype")!, secondLabel: "Antihype", lineA: ["1 Kokenov", "5 Muslim", "6 Zhiembay", "8 Saynov", "8 Sagyndyk", "9 Ospanov", "10 Zhapay", "16 Omirzak"], lineB: ["1 Zangar", "4 Abuov", "7 Islamkhan", "8 Alisher", "9 Akhmetov", "17 Merei", "21 Kuanov", "22 Orazaly"], infoA: ["N.Zhiembay", "S.Omirzak"], infoB: ["", ""]),
        Games.init(firstLabel: "Sunkar", firstImage: UIImage(named: "Sunkar")!, middleLabel: "4:1", secondImage: UIImage(named: "Nomad JR")!, secondLabel: "Nomad JR", lineA: ["1 Tashenov", "3 Askhat", "4 Kalilulin", "7 Tursynbaev", "8 Ali", "9 Otep", "10 Roma", "11 Kama", "17 Bolat", "21 Sharapov"], lineB: ["Balkhisov 1", "Rinatov  3", "Guzalin 4", "Kolesnik 7", "Smailov 8", "Kanatbekuly 9", "Sagaladinov 10", "Lesbek 11", "Zhasan 17", "Makat 21"], infoA: ["", "Z.Amangeldeyev", "B.Erkhanov", "E.Izbergen", "F.Batyrkhan"], infoB: ["D.Amirkhanov", "", "", "", ""]),
        
        Games.init(firstLabel: "Kentau", firstImage: UIImage(named: "Kentau")!, middleLabel: "2:2", secondImage: UIImage(named: "Evolution")!, secondLabel: "Evolution", lineA: ["1 Alpamys", "3 Ayagan", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Bairamov 1", "Bekzat  3", "Berdikul 4", "Bissen 7", "Bissenbayev 8", "Sungkar 9", "Gizatov 10", "Maksatov 11", "Danabaev 17", "Kalekes 21"], infoA: ["B.Omarbek", "", "", "B.Asangali"], infoB: ["", "A.Aman", "A.Abaidullin", ""]),
        Games.init(firstLabel: "Sparta", firstImage: UIImage(named: "Sparta")!, middleLabel: "8:3", secondImage: UIImage(named: "Nomad")!, secondLabel: "Nomad", lineA: ["1 Ordabek", "3 Irisbayev", "4 Kokenov", "7 Bektemir", "8 Orman", "9 Ashirkhan", "10 Khametov", "11 Kemelkhan", "17 Khassen", "21 Kuandyk"], lineB: ["Murat 1", "Meirkhan  3", "Mukatay 4", "Kydyraliev 7", "Mamatov 8", "Omarov 9", "Sadyk 10", "Saparkhan 11", "Senalov 17", "Suyunov 21"], infoA: ["Z.Nurtuganov", "Z.Nurtuganov", "", "", "", "A.Ongarbay", "Z.Nurtuganov", "S.Torehanov(OG)", "D.Khametov", "B.Gazizov", "Z.Nurtuganov"], infoB: ["", "", "B.Ibrahim", "B.Kobilan", "Z.Nakypbek", "", "", "", "", "", ""]),
        Games.init(firstLabel: "Teachers", firstImage: UIImage(named: "Teachers")!, middleLabel: "2:0", secondImage: UIImage(named: "Rizo")!, secondLabel: "Rizo", lineA: ["1 Tangirkul", "3 Yerkeshov", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Urmanov 1", "Yerkinbek  3", "Zhumashev 4", "Mussin 7", "Kokenov 8", "Gotye 9", "Ulanov 10", "Sapargali 11", "Kabi 17", "Kenes 21"], infoA: ["Z.Agybai", "S.Vankeyev"], infoB: ["", ""]),
        Games.init(firstLabel: "Avangar", firstImage: UIImage(named: "Avangar")!, middleLabel: "1:2", secondImage: UIImage(named: "Barabar")!, secondLabel: "Barabar", lineA: ["1 Kuanysh", "3 Sagyngaly", "4 Azamat", "7 Kupesov", "8 Beibit", "9 Ospanov", "10 Imangazin", "11 Makhmutov", "17 Inkar", "21 Agmanov"], lineB: ["Zheksengaliev 1", "Ozhanov 3", "Nurtazayev 4", "Kanatov 7", "Kenzhebulatov 8", "Shah 9", "Zhumabekov 10", "Utarbaev 11", "Tagayev 17", "Serikov 21"], infoA: ["", "", "S.Azamat"], infoB: ["A.Temirbolat", "A.Temirbolat", ""]),
        Games.init(firstLabel: "Nation Army", firstImage: UIImage(named: "Nation Army")!, middleLabel: "0:2", secondImage: UIImage(named: "Alash")!, secondLabel: "Alash", lineA: ["1 Nurpeis", "3 Muratuly", "4 Muratkhan", "7 Otep", "8 Sabitov", "9 Kessikbayev", "10 Irisbayev", "11 Ganshin", "17 Bolatay", "21 Demenov"], lineB: ["Maratov 1", "Zhailybai  3", "Alibekov 4", "Begimbetov 7", "Zhekeev 8", "Bigaliev 9", "Djabasov 10", "Shukatov 11", "Nurpoldin 17", "Zholdin 21"], infoA: ["", ""], infoB: ["M.Seitov", "M.Seitov"]),
        Games.init(firstLabel: "Leicester", firstImage: UIImage(named: "Leicester")!, middleLabel: "2:0", secondImage: UIImage(named: "Antihype")!, secondLabel: "Antihype", lineA: ["1 Kokenov", "5 Muslim", "6 Zhiembay", "8 Saynov", "8 Sagyndyk", "9 Ospanov", "10 Zhapay", "16 Omirzak"], lineB: ["1 Zangar", "4 Abuov", "7 Islamkhan", "8 Alisher", "9 Akhmetov", "17 Merei", "21 Kuanov", "22 Orazaly"], infoA: ["N.Zhiembay", "S.Omirzak"], infoB: ["", ""]),
        Games.init(firstLabel: "Sunkar", firstImage: UIImage(named: "Sunkar")!, middleLabel: "4:1", secondImage: UIImage(named: "Nomad JR")!, secondLabel: "Nomad JR", lineA: ["1 Tashenov", "3 Askhat", "4 Kalilulin", "7 Tursynbaev", "8 Ali", "9 Otep", "10 Roma", "11 Kama", "17 Bolat", "21 Sharapov"], lineB: ["Balkhisov 1", "Rinatov  3", "Guzalin 4", "Kolesnik 7", "Smailov 8", "Kanatbekuly 9", "Sagaladinov 10", "Lesbek 11", "Zhasan 17", "Makat 21"], infoA: ["", "Z.Amangeldeyev", "B.Erkhanov", "E.Izbergen", "F.Batyrkhan"], infoB: ["D.Amirkhanov", "", "", "", ""]),
        
        Games.init(firstLabel: "Kentau", firstImage: UIImage(named: "Kentau")!, middleLabel: "2:2", secondImage: UIImage(named: "Evolution")!, secondLabel: "Evolution", lineA: ["1 Alpamys", "3 Ayagan", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Bairamov 1", "Bekzat  3", "Berdikul 4", "Bissen 7", "Bissenbayev 8", "Sungkar 9", "Gizatov 10", "Maksatov 11", "Danabaev 17", "Kalekes 21"], infoA: ["B.Omarbek", "", "", "B.Asangali"], infoB: ["", "A.Aman", "A.Abaidullin", ""]),
        Games.init(firstLabel: "Sparta", firstImage: UIImage(named: "Sparta")!, middleLabel: "8:3", secondImage: UIImage(named: "Nomad")!, secondLabel: "Nomad", lineA: ["1 Ordabek", "3 Irisbayev", "4 Kokenov", "7 Bektemir", "8 Orman", "9 Ashirkhan", "10 Khametov", "11 Kemelkhan", "17 Khassen", "21 Kuandyk"], lineB: ["Murat 1", "Meirkhan  3", "Mukatay 4", "Kydyraliev 7", "Mamatov 8", "Omarov 9", "Sadyk 10", "Saparkhan 11", "Senalov 17", "Suyunov 21"], infoA: ["Z.Nurtuganov", "Z.Nurtuganov", "", "", "", "A.Ongarbay", "Z.Nurtuganov", "S.Torehanov(OG)", "D.Khametov", "B.Gazizov", "Z.Nurtuganov"], infoB: ["", "", "B.Ibrahim", "B.Kobilan", "Z.Nakypbek", "", "", "", "", "", ""]),
        Games.init(firstLabel: "Teachers", firstImage: UIImage(named: "Teachers")!, middleLabel: "2:0", secondImage: UIImage(named: "Rizo")!, secondLabel: "Rizo", lineA: ["1 Tangirkul", "3 Yerkeshov", "4 Adiat", "7 Nurali", "8 Askar", "9 Ashirkhan", "10 Aitullayev", "11 Asangali", "17 Ayazbekov", "21 Bagitov"], lineB: ["Urmanov 1", "Yerkinbek  3", "Zhumashev 4", "Mussin 7", "Kokenov 8", "Gotye 9", "Ulanov 10", "Sapargali 11", "Kabi 17", "Kenes 21"], infoA: ["Z.Agybai", "S.Vankeyev"], infoB: ["", ""]),
        Games.init(firstLabel: "Avangar", firstImage: UIImage(named: "Avangar")!, middleLabel: "1:2", secondImage: UIImage(named: "Barabar")!, secondLabel: "Barabar", lineA: ["1 Kuanysh", "3 Sagyngaly", "4 Azamat", "7 Kupesov", "8 Beibit", "9 Ospanov", "10 Imangazin", "11 Makhmutov", "17 Inkar", "21 Agmanov"], lineB: ["Zheksengaliev 1", "Ozhanov 3", "Nurtazayev 4", "Kanatov 7", "Kenzhebulatov 8", "Shah 9", "Zhumabekov 10", "Utarbaev 11", "Tagayev 17", "Serikov 21"], infoA: ["", "", "S.Azamat"], infoB: ["A.Temirbolat", "A.Temirbolat", ""]),
        Games.init(firstLabel: "Nation Army", firstImage: UIImage(named: "Nation Army")!, middleLabel: "0:2", secondImage: UIImage(named: "Alash")!, secondLabel: "Alash", lineA: ["1 Nurpeis", "3 Muratuly", "4 Muratkhan", "7 Otep", "8 Sabitov", "9 Kessikbayev", "10 Irisbayev", "11 Ganshin", "17 Bolatay", "21 Demenov"], lineB: ["Maratov 1", "Zhailybai  3", "Alibekov 4", "Begimbetov 7", "Zhekeev 8", "Bigaliev 9", "Djabasov 10", "Shukatov 11", "Nurpoldin 17", "Zholdin 21"], infoA: ["", ""], infoB: ["M.Seitov", "M.Seitov"]),
        Games.init(firstLabel: "Leicester", firstImage: UIImage(named: "Leicester")!, middleLabel: "2:0", secondImage: UIImage(named: "Antihype")!, secondLabel: "Antihype", lineA: ["1 Kokenov", "5 Muslim", "6 Zhiembay", "8 Saynov", "8 Sagyndyk", "9 Ospanov", "10 Zhapay", "16 Omirzak"], lineB: ["1 Zangar", "4 Abuov", "7 Islamkhan", "8 Alisher", "9 Akhmetov", "17 Merei", "21 Kuanov", "22 Orazaly"], infoA: ["N.Zhiembay", "S.Omirzak"], infoB: ["", ""]),
        Games.init(firstLabel: "Sunkar", firstImage: UIImage(named: "Sunkar")!, middleLabel: "4:1", secondImage: UIImage(named: "Nomad JR")!, secondLabel: "Nomad JR", lineA: ["1 Tashenov", "3 Askhat", "4 Kalilulin", "7 Tursynbaev", "8 Ali", "9 Otep", "10 Roma", "11 Kama", "17 Bolat", "21 Sharapov"], lineB: ["Balkhisov 1", "Rinatov  3", "Guzalin 4", "Kolesnik 7", "Smailov 8", "Kanatbekuly 9", "Sagaladinov 10", "Lesbek 11", "Zhasan 17", "Makat 21"], infoA: ["", "Z.Amangeldeyev", "B.Erkhanov", "E.Izbergen", "F.Batyrkhan"], infoB: ["D.Amirkhanov", "", "", "", ""]),
    ]
}

